name: Add Scam Domain
description: Suggest a scam domain to add to the list.
title: "[Add Domain] "
labels: ["add-domain"]
body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm these items before submitting your request
      options:
        - label: I have checked that this domain is not already in the list.
          required: true
        - label: I understand that submitting a domain does not guarantee its addition to the list.
          required: true
  - type: input
    id: domain
    attributes:
      label: Domain
      description: "Enter the scam domain (e.g., `scam-example.com`)"
      placeholder: scam-example.com
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context (Optional)
      description: "Any proof or reason why this domain is a scam?"
      placeholder: "Please provide any relevant details or context."
    validations:
      required: false