name: Validate Pull Request

on:
  pull_request:
    branches: [main]
    paths:
      - 'list.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for duplicates
        run: |
          jq 'group_by(.) | map(select(length > 1)) | if length > 0 then error("❌ Duplicates found.") else "✅ No duplicates." end' list.json

      - name: Check if sorted
        run: |
          diff <(jq -c 'sort' list.json) <(jq -c '.' list.json) \
          || (echo "❌ list.json is not sorted."; exit 1)
