name: Validate Domain PR

on:
  pull_request:
    branches: [main]
    paths: ["list.json"]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Check for duplicates
        run: |
          jq 'group_by(.) | map(select(length > 1)) | if length > 0 then error("❌ Duplicates found.") else "✅ No duplicates." end' list.json

      - name: Ensure list is sorted A-Z
        run: |
          diff <(jq -c 'sort' list.json) <(jq -c '.' list.json) \
          && echo "✅ list.json is sorted." \
          || (echo "❌ list.json is not sorted."; exit 1)
